/*
 * Copyright 2014 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.baidu.cc.configuration.bo;

import com.baidu.bjf.dao.ColumnDescription;
import com.baidu.bjf.dao.FieldAccessVo;
import com.baidu.bjf.dao.Id;
import com.baidu.lego.web.spi.component.TableDataConvertable;
import com.baidu.lego.web.spi.component.TableField;
import com.baidu.rigel.platform.util.DateUtils;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.WeakHashMap;

import org.apache.commons.lang.ObjectUtils;

/**
 * This bo is map to table : config_item Table description : .
 * 
 * @author BJF
 */
public abstract class ConfigItemBase extends FieldAccessVo implements
        TableDataConvertable, Serializable {
    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column config_item.id
     * 
     * @mbggenerated
     */
    private static final String PROPERTY_ID = "id";

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column config_item.name
     * 
     * @mbggenerated
     */
    private static final String PROPERTY_NAME = "name";

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column config_item.memo
     * 
     * @mbggenerated
     */
    private static final String PROPERTY_MEMO = "memo";

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column config_item.val
     * 
     * @mbggenerated
     */
    private static final String PROPERTY_VAL = "val";

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column config_item.shareable
     * 
     * @mbggenerated
     */
    private static final String PROPERTY_SHAREABLE = "shareable";

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column config_item.ref
     * 
     * @mbggenerated
     */
    private static final String PROPERTY_REF = "ref";

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column config_item.create_time
     * 
     * @mbggenerated
     */
    private static final String PROPERTY_CREATETIME = "createTime";

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column config_item.update_time
     * 
     * @mbggenerated
     */
    private static final String PROPERTY_UPDATETIME = "updateTime";

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column config_item.group_id
     * 
     * @mbggenerated
     */
    private static final String PROPERTY_GROUPID = "groupId";

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column config_item.version_id
     * 
     * @mbggenerated
     */
    private static final String PROPERTY_VERSIONID = "versionId";

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column config_item.id
     * 
     * @mbggenerated
     */
    private static final String PROPERTY_REMARK_ID = "主键";

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column config_item.name
     * 
     * @mbggenerated
     */
    private static final String PROPERTY_REMARK_NAME = "配置名称";

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column config_item.memo
     * 
     * @mbggenerated
     */
    private static final String PROPERTY_REMARK_MEMO = "备注";

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column config_item.val
     * 
     * @mbggenerated
     */
    private static final String PROPERTY_REMARK_VAL = "配置值";

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column config_item.shareable
     * 
     * @mbggenerated
     */
    private static final String PROPERTY_REMARK_SHAREABLE = "是否共享";

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column config_item.ref
     * 
     * @mbggenerated
     */
    private static final String PROPERTY_REMARK_REF = "是否引用值";

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column config_item.create_time
     * 
     * @mbggenerated
     */
    private static final String PROPERTY_REMARK_CREATETIME = "创建时间";

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column config_item.update_time
     * 
     * @mbggenerated
     */
    private static final String PROPERTY_REMARK_UPDATETIME = "更新时间";

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column config_item.group_id
     * 
     * @mbggenerated
     */
    private static final String PROPERTY_REMARK_GROUPID = "分组id";

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column config_item.version_id
     * 
     * @mbggenerated
     */
    private static final String PROPERTY_REMARK_VERSIONID = "versionID";

    /** serial Version UID. */
    private static final long serialVersionUID = -1L;

    /** hashCode temporary storage. */
    private volatile Long hashCode;

    /**
     * Use a WeakHashMap so entries will be garbage collected once all entities
     * referring to a saved hash are garbage collected themselves.
     */
    private static final Map<Serializable, Long> SAVED_HASHES = Collections
            .synchronizedMap(new WeakHashMap<Serializable, Long>());

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column config_item.id
     * 
     * @mbggenerated
     */
    @ColumnDescription(desc = PROPERTY_REMARK_ID)
    @Id
    private Long id;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column config_item.name
     * 
     * @mbggenerated
     */
    @ColumnDescription(desc = PROPERTY_REMARK_NAME)
    private String name;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column config_item.memo
     * 
     * @mbggenerated
     */
    @ColumnDescription(desc = PROPERTY_REMARK_MEMO)
    private String memo;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column config_item.val
     * 
     * @mbggenerated
     */
    @ColumnDescription(desc = PROPERTY_REMARK_VAL)
    private String val;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column config_item.shareable
     * 
     * @mbggenerated
     */
    @ColumnDescription(desc = PROPERTY_REMARK_SHAREABLE)
    private Boolean shareable;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column config_item.ref
     * 
     * @mbggenerated
     */
    @ColumnDescription(desc = PROPERTY_REMARK_REF)
    private Boolean ref;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column config_item.create_time
     * 
     * @mbggenerated
     */
    @ColumnDescription(desc = PROPERTY_REMARK_CREATETIME)
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column config_item.update_time
     * 
     * @mbggenerated
     */
    @ColumnDescription(desc = PROPERTY_REMARK_UPDATETIME)
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column config_item.group_id
     * 
     * @mbggenerated
     */
    @ColumnDescription(desc = PROPERTY_REMARK_GROUPID)
    private Long groupId;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column config_item.version_id
     * 
     * @mbggenerated
     */
    @ColumnDescription(desc = PROPERTY_REMARK_VERSIONID)
    private Long versionId;

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column config_item.id
     * 
     * @return the value of config_item.id
     * 
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column config_item.id
     * 
     * @param id
     *            the value for config_item.id
     * 
     * @mbggenerated
     */
    public void setId(Long id) {
        // If we've just been persisted and hashCode has been
        // returned then make sure other entities with this
        // ID return the already returned hash code
        if (this.id == null && id != null && this.hashCode != null) {
            SAVED_HASHES.put(id, this.hashCode);
        }
        if (!ObjectUtils.equals(id, this.id)) {
            getChangeLogInfo().put(PROPERTY_ID, id);
        }
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column config_item.name
     * 
     * @return the value of config_item.name
     * 
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column config_item.name
     * 
     * @param name
     *            the value for config_item.name
     * 
     * @mbggenerated
     */
    public void setName(String name) {
        if (!ObjectUtils.equals(name, this.name)) {
            getChangeLogInfo().put(PROPERTY_NAME, name);
        }
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column config_item.memo
     * 
     * @return the value of config_item.memo
     * 
     * @mbggenerated
     */
    public String getMemo() {
        return memo;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column config_item.memo
     * 
     * @param memo
     *            the value for config_item.memo
     * 
     * @mbggenerated
     */
    public void setMemo(String memo) {
        if (!ObjectUtils.equals(memo, this.memo)) {
            getChangeLogInfo().put(PROPERTY_MEMO, memo);
        }
        this.memo = memo;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column config_item.val
     * 
     * @return the value of config_item.val
     * 
     * @mbggenerated
     */
    public String getVal() {
        return val;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column config_item.val
     * 
     * @param val
     *            the value for config_item.val
     * 
     * @mbggenerated
     */
    public void setVal(String val) {
        if (!ObjectUtils.equals(val, this.val)) {
            getChangeLogInfo().put(PROPERTY_VAL, val);
        }
        this.val = val;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column config_item.shareable
     * 
     * @return the value of config_item.shareable
     * 
     * @mbggenerated
     */
    public Boolean getShareable() {
        return shareable;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column config_item.shareable
     * 
     * @param shareable
     *            the value for config_item.shareable
     * 
     * @mbggenerated
     */
    public void setShareable(Boolean shareable) {
        if (!ObjectUtils.equals(shareable, this.shareable)) {
            getChangeLogInfo().put(PROPERTY_SHAREABLE, shareable);
        }
        this.shareable = shareable;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column config_item.ref
     * 
     * @return the value of config_item.ref
     * 
     * @mbggenerated
     */
    public Boolean getRef() {
        return ref;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column config_item.ref
     * 
     * @param ref
     *            the value for config_item.ref
     * 
     * @mbggenerated
     */
    public void setRef(Boolean ref) {
        if (!ObjectUtils.equals(ref, this.ref)) {
            getChangeLogInfo().put(PROPERTY_REF, ref);
        }
        this.ref = ref;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column config_item.create_time
     * 
     * @return the value of config_item.create_time
     * 
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column config_item.create_time
     * 
     * @param createTime
     *            the value for config_item.create_time
     * 
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        if (!ObjectUtils.equals(createTime, this.createTime)) {
            getChangeLogInfo().put(PROPERTY_CREATETIME, createTime);
        }
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column config_item.update_time
     * 
     * @return the value of config_item.update_time
     * 
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column config_item.update_time
     * 
     * @param updateTime
     *            the value for config_item.update_time
     * 
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        if (!ObjectUtils.equals(updateTime, this.updateTime)) {
            getChangeLogInfo().put(PROPERTY_UPDATETIME, updateTime);
        }
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column config_item.group_id
     * 
     * @return the value of config_item.group_id
     * 
     * @mbggenerated
     */
    public Long getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column config_item.group_id
     * 
     * @param groupId
     *            the value for config_item.group_id
     * 
     * @mbggenerated
     */
    public void setGroupId(Long groupId) {
        if (!ObjectUtils.equals(groupId, this.groupId)) {
            getChangeLogInfo().put(PROPERTY_GROUPID, groupId);
        }
        this.groupId = groupId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column config_item.version_id
     * 
     * @return the value of config_item.version_id
     * 
     * @mbggenerated
     */
    public Long getVersionId() {
        return versionId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column config_item.version_id
     * 
     * @param versionId
     *            the value for config_item.version_id
     * 
     * @mbggenerated
     */
    public void setVersionId(Long versionId) {
        if (!ObjectUtils.equals(versionId, this.versionId)) {
            getChangeLogInfo().put(PROPERTY_VERSIONID, versionId);
        }
        this.versionId = versionId;
    }

    /**
     * get table fields.
     * 
     * @return list of TableField
     */
    public List<TableField> getTableFieds() {
        List<TableField> list = new ArrayList<TableField>(10);
        TableField tf;
        tf = new TableField(PROPERTY_REMARK_ID, PROPERTY_ID);
        list.add(tf);
        tf = new TableField(PROPERTY_REMARK_NAME, PROPERTY_NAME);
        list.add(tf);
        tf = new TableField(PROPERTY_REMARK_MEMO, PROPERTY_MEMO);
        list.add(tf);
        tf = new TableField(PROPERTY_REMARK_VAL, PROPERTY_VAL);
        list.add(tf);
        tf = new TableField(PROPERTY_REMARK_SHAREABLE, PROPERTY_SHAREABLE);
        list.add(tf);
        tf = new TableField(PROPERTY_REMARK_REF, PROPERTY_REF);
        list.add(tf);
        tf = new TableField(PROPERTY_REMARK_CREATETIME, PROPERTY_CREATETIME);
        list.add(tf);
        tf = new TableField(PROPERTY_REMARK_UPDATETIME, PROPERTY_UPDATETIME);
        list.add(tf);
        tf = new TableField(PROPERTY_REMARK_GROUPID, PROPERTY_GROUPID);
        list.add(tf);
        tf = new TableField(PROPERTY_REMARK_VERSIONID, PROPERTY_VERSIONID);
        list.add(tf);
        return list;
    }

    /**
     * get table values.
     * 
     * @return Map
     */
    public Map<String, Object> getTableValue() {
        Map<String, Object> map = new HashMap<String, Object>();
        map.put(PROPERTY_ID, id);
        map.put(PROPERTY_NAME, name);
        map.put(PROPERTY_MEMO, memo);
        map.put(PROPERTY_VAL, val);
        map.put(PROPERTY_SHAREABLE, shareable);
        map.put(PROPERTY_REF, ref);
        map.put(PROPERTY_CREATETIME,
                DateUtils.formatDate(createTime, DateUtils.DEFAULT_PATTERN));
        map.put(PROPERTY_UPDATETIME,
                DateUtils.formatDate(updateTime, DateUtils.DEFAULT_PATTERN));
        map.put(PROPERTY_GROUPID, groupId);
        map.put(PROPERTY_VERSIONID, versionId);
        return map;
    }

    /**
     * get map key is field name, value is field value.
     * 
     * @return Map
     */
    public Map<String, Object> toMap() {
        Map<String, Object> map = new HashMap<String, Object>();
        map.put(PROPERTY_ID, id);
        map.put(PROPERTY_NAME, name);
        map.put(PROPERTY_MEMO, memo);
        map.put(PROPERTY_VAL, val);
        map.put(PROPERTY_SHAREABLE, shareable);
        map.put(PROPERTY_REF, ref);
        map.put(PROPERTY_CREATETIME, createTime);
        map.put(PROPERTY_UPDATETIME, updateTime);
        map.put(PROPERTY_GROUPID, groupId);
        map.put(PROPERTY_VERSIONID, versionId);
        return map;
    }

    /*
     * (non-Javadoc)
     * 
     * @see java.lang.Object#hashCode()
     */
    @Override
    public int hashCode() {
        if (this.hashCode == null) {
            synchronized (this) {
                if (this.hashCode == null) {
                    Long newHashCode = null;
                    if (getId() != null) {
                        newHashCode = SAVED_HASHES.get(getId());
                    }

                    if (newHashCode == null) {
                        if (getId() != null) {
                            newHashCode = (long) getId().hashCode();
                        } else {
                            newHashCode = (long) super.hashCode();
                        }
                    }
                    this.hashCode = newHashCode;
                }
            }
        }
        return (int) (this.hashCode & 0xffffff);
    }

    /*
     * (non-Javadoc)
     * 
     * @see java.lang.Object#equals(java.lang.Object)
     */
    @Override
    public boolean equals(final Object aThat) {

        if (this == aThat) {
            return true;
        }
        if (aThat == null) {
            return false;
        }
        if (!(aThat instanceof ConfigItemBase)) {
            return false;
        }

        final ConfigItemBase THAT = (ConfigItemBase) aThat;
        boolean result = true;
        result = result
                && (((this.getId() == null) && (THAT.getId() == null)) || (this
                        .getId() != null && this.getId().equals(THAT.getId())));
        return result;
    }
}